import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
    en: {
        overview: "Overview",
        live_map: "Live Map",
        analytics: "Analytics",
        smart_bins: "Smart Bins",
        settings: "Settings",
        total_bins: "Total Bins",
        full_bins: "Full Bins",
        low_battery: "Low Battery",
        system_health: "System Health",
        active_bins_in: "active smart bins in",
        hub_id: "Hub ID",
        needs_cleanup: "Needs Cleanup",
        healthy: "Healthy",
        current_level: "Current Level",
        navigate_to_bin: "Navigate to Bin",
        add_bin: "Add Bin",
        logout: "Logout",
        account_info: "Account Information",
        username: "Username",
        email: "Email",
        city: "City",
        state: "State",
        place: "Place",
        appearance: "Appearance",
        theme: "Theme",
        language: "Language",
        security: "Security",
        change_password: "Change Password",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_password: "Confirm Password",
        update_password: "Update Password",
        dark: "Dark",
        light: "Light",
        system_status: "System Status",
        all_systems_online: "All Systems Online"
    },
    hi: {
        overview: "अवलोकन",
        live_map: "लाइव नक्शा",
        analytics: "विश्लेषण",
        smart_bins: "स्मार्ट डस्टबिन",
        settings: "सेटिंग्स",
        total_bins: "कुल डस्टबिन",
        full_bins: "भरे हुए डस्टबिन",
        low_battery: "कम बैटरी",
        system_health: "सिस्टम स्वास्थ्य",
        active_bins_in: "सक्रिय स्मार्ट डस्टबिन",
        hub_id: "हब आईडी",
        needs_cleanup: "सफाई की आवश्यकता",
        healthy: "स्वस्थ",
        current_level: "वर्तमान स्तर",
        navigate_to_bin: "डस्टबिन पर जाएं",
        add_bin: "डस्टबिन जोड़ें",
        logout: "लॉगआउट",
        account_info: "खाता जानकारी",
        username: "उपयोगकर्ता नाम",
        email: "ईमेल",
        city: "शहर",
        state: "राज्य",
        place: "स्थान",
        appearance: "रूप-रंग",
        theme: "थीम",
        language: "भाषा",
        security: "सुरक्षा",
        change_password: "पासवर्ड बदलें",
        current_password: "वर्तमान पासवर्ड",
        new_password: "नया पासवर्ड",
        confirm_password: "पासवर्ड की पुष्टि करें",
        update_password: "पासवर्ड अपडेट करें",
        dark: "डार्क",
        light: "लाइट",
        system_status: "सिस्टम की स्थिति",
        all_systems_online: "सभी सिस्टम ऑनलाइन हैं"
    },
    bn: {
        overview: "সংক্ষিপ্ত বিবরণ",
        live_map: "লাইভ ম্যাপ",
        analytics: "বিশ্লেষণ",
        smart_bins: "স্মার্ট বিন",
        settings: "সেটিংস",
        total_bins: "মোট বিন",
        full_bins: "ভর্তি বিন",
        low_battery: "কম ব্যাটারি",
        system_health: "সিস্টেম স্বাস্থ্য",
        active_bins_in: "সক্রিয় স্মার্ট বিন",
        hub_id: "হাব আইডি",
        needs_cleanup: "পরিষ্কার করা প্রয়োজন",
        healthy: "স্বাস্থ্যকর",
        current_level: "বর্তমান স্তর",
        navigate_to_bin: "বিনে যান",
        add_bin: "বিন যোগ করুন",
        logout: "লগআউট",
        account_info: "অ্যাকাউন্টের তথ্য",
        username: "ব্যবহারকারীর নাম",
        email: "ইমেল",
        city: "শহর",
        state: "রাজ্য",
        place: "স্থান",
        appearance: "চেহারা",
        theme: "থিম",
        language: "ভাষা",
        security: "নিরাপত্তা",
        change_password: "পাসওয়ার্ড পরিবর্তন করুন",
        current_password: "বর্তমান পাসওয়ার্ড",
        new_password: "নতুন পাসওয়ার্ড",
        confirm_password: "পাসওয়ার্ড নিশ্চিত করুন",
        update_password: "পাসওয়ার্ড আপডেট করুন",
        dark: "ডার্ক",
        light: "লাইট",
        system_status: "সিস্টেম স্ট্যাটাস",
        all_systems_online: "সমস্ত সিস্টেম অনলাইন"
    },
    te: {
        overview: "అవలోకనం",
        live_map: "లైవ్ మ్యాప్",
        analytics: "విశ్లేషణ",
        smart_bins: "స్మార్ట్ బిన్స్",
        settings: "సెట్టింగులు",
        total_bins: "మొత్తం బిన్స్",
        full_bins: "నిండిన బిన్స్",
        low_battery: "తక్కువ బ్యాటరీ",
        system_health: "సిస్టమ్ ఆరోగ్యం",
        active_bins_in: "క్రియాశీల స్మార్ట్ బిన్స్",
        hub_id: "హబ్ ఐడి",
        needs_cleanup: "శుభ్రత అవసరం",
        healthy: "ఆరోగ్యకరమైనది",
        current_level: "ప్రస్తుత స్థాయి",
        navigate_to_bin: "బిన్ వైపు వెళ్ళండి",
        add_bin: "బిన్ జోడించు",
        logout: "లాగ్అవుట్",
        account_info: "ఖాతా సమాచారం",
        username: "వినియోగదారు పేరు",
        email: "ఈమెయిల్",
        city: "నగరం",
        state: "రాష్ట్రం",
        place: "స్థలం",
        appearance: "రూపం",
        theme: "థీమ్",
        language: "భాష",
        security: "భద్రత",
        change_password: "పాస్వర్డ్ మార్చండి",
        current_password: "ప్రస్తుత పాస్వర్డ్",
        new_password: "కొత్త పాస్వర్డ్",
        confirm_password: "పాస్వర్డ్ నిర్ధారించండి",
        update_password: "పాస్వర్డ్ అప్డేట్ చేయండి",
        dark: "డార్క్",
        light: "లైట్",
        system_status: "సిస్టమ్ స్థితి",
        all_systems_online: "అన్ని సిస్టమ్స్ ఆన్లైన్"
    },
    mr: {
        overview: "आढावा",
        live_map: "थेट नकाशा",
        analytics: "विश्लेषण",
        smart_bins: "स्मार्ट डस्टबिन",
        settings: "सेटिंग्स",
        total_bins: "एकूण डस्टबिन",
        full_bins: "भरलेले डस्टबिन",
        low_battery: "कमी बॅटरी",
        system_health: "सिस्टम आरोग्य",
        active_bins_in: "सक्रिय स्मार्ट डस्टबिन",
        hub_id: "हब आयडी",
        needs_cleanup: "स्वच्छतेची गरज",
        healthy: "चांगले",
        current_level: "सध्याची पातळी",
        navigate_to_bin: "डस्टबिनकडे जा",
        add_bin: "डस्टबिन जोडा",
        logout: "लॉगआउट",
        account_info: "खाते माहिती",
        username: "वापरकर्ता नाव",
        email: "ईमेल",
        city: "शहर",
        state: "राज्य",
        place: "ठिकाण",
        appearance: "देखावा",
        theme: "थीम",
        language: "भाषा",
        security: "सुरक्षा",
        change_password: "पासवर्ड बदला",
        current_password: "सध्याचा पासवर्ड",
        new_password: "नवीन पासवर्ड",
        confirm_password: "पासवर्डची पुष्टी करा",
        update_password: "पासवर्ड अपडेट करा",
        dark: "डार्क",
        light: "लाईट",
        system_status: "सिस्टम स्थिती",
        all_systems_online: "सर्व सिस्टम ऑनलाइन"
    },
    ta: {
        overview: "மேலோட்டம்",
        live_map: "நேரடி வரைபடம்",
        analytics: "பகுப்பாய்வு",
        smart_bins: "ஸ்மார்ட் குப்பைத் தொட்டிகள்",
        settings: "அமைப்புகள்",
        total_bins: "மொத்த தொட்டிகள்",
        full_bins: "நிறைந்த தொட்டிகள்",
        low_battery: "குறைந்த பேட்டரி",
        system_health: "கணினி ஆரோக்கியம்",
        active_bins_in: "செயலில் உள்ள ஸ்மார்ட் தொட்டிகள்",
        hub_id: "ஹப் ஐடி",
        needs_cleanup: "சுத்தம் தேவை",
        healthy: "ஆரோக்கியமானது",
        current_level: "தற்போதைய நிலை",
        navigate_to_bin: "தொட்டிக்குச் செல்லவும்",
        add_bin: "தொட்டியைச் சேர்க்கவும்",
        logout: "வெளியேறு",
        account_info: "கணக்கு விவரங்கள்",
        username: "பயனர் பெயர்",
        email: "மின்னஞ்சல்",
        city: "நகரம்",
        state: "மாநிலம்",
        place: "இடம்",
        appearance: "தோற்றம்",
        theme: "தீம்",
        language: "மொழி",
        security: "பாதுகாப்பு",
        change_password: "கடவுச்சொல்லை மாற்றவும்",
        current_password: "தற்போதைய கடவுச்சொல்",
        new_password: "புதிய கடவுச்சொல்",
        confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்து",
        update_password: "கடவுச்சொல்லை மாற்றவும்",
        dark: "டார்க்",
        light: "லைட்",
        system_status: "கணினி நிலை",
        all_systems_online: "அனைத்து அமைப்புகளும் ஆன்லைனில்"
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('lang', lang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage, languages: Object.keys(translations) }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
